Use caml_failwith instead of failwith to prevent linking errors
such as:

> # /usr/bin/ld: src/compiler/.main.eobjs/native/dune__exe__Main.o: warning: relocation in read-only section `.text'
> # /usr/bin/ld: /home/opam/.opam/4.14/lib/stdint/libstdint_stubs.a(int32_conv.o): in function `int32_of_int128':
> # /home/opam/.opam/4.14/.opam-switch/build/stdint.0.7.1/_build/default/lib/int32_conv.c:108: undefined reference to `failwith'

and so on.